Config.ItemList = {
	['at_flashlight_pistol'] = { component = {`COMPONENT_AT_PI_FLSH`}, useTime = 2500 },
	['at_flashlight_rifle'] = { component = {`COMPONENT_AT_AR_FLSH`}, useTime = 2500 },
	['at_flashlight_shotgun'] = { component = {`COMPONENT_AT_AR_FLSH`}, useTime = 2500 },
	['at_flashlight_smg'] = { component = {`COMPONENT_AT_AR_FLSH`, `COMPONENT_AT_PI_FLSH`}, useTime = 2500 },
	['at_flashlight_sniper'] = { component = {`COMPONENT_AT_AR_FLSH`}, useTime = 2500 },
	['at_flashlight_mg'] = { component = {`COMPONENT_AT_AR_FLSH`}, useTime = 2500 },
	['at_clip_extended_pistol'] = { component = {`COMPONENT_PISTOL_CLIP_02`, `COMPONENT_PISTOL_MK2_CLIP_02`, `COMPONENT_SNSPISTOL_MK2_CLIP_02`, `COMPONENT_COMBATPISTOL_CLIP_02`, `COMPONENT_PISTOL50_CLIP_02`, `COMPONENT_HEAVYPISTOL_CLIP_02`, `COMPONENT_SNSPISTOL_CLIP_02`, `COMPONENT_VINTAGEPISTOL_CLIP_02`, `COMPONENT_MACHINEPISTOL_CLIP_02`}, useTime = 2500 },
	['at_clip_extended_smg'] = { component = {`COMPONENT_SMG_CLIP_02`, `COMPONENT_ASSAULTSMG_CLIP_02`, `COMPONENT_MICROSMG_CLIP_02`, `COMPONENT_MINISMG_CLIP_02`, `COMPONENT_COMBATPDW_CLIP_02`}, useTime = 2500 },
	['at_clip_extended_shotgun'] = { component = {`COMPONENT_HEAVYSHOTGUN_CLIP_02`}, useTime = 2500 },
	['at_clip_extended_rifle'] = { component = {`COMPONENT_ASSAULTRIFLE_CLIP_02`, `COMPONENT_CARBINERIFLE_CLIP_02`, `COMPONENT_ADVANCEDRIFLE_CLIP_02`, `COMPONENT_SPECIALCARBINE_CLIP_02`, `COMPONENT_BULLPUPRIFLE_CLIP_02`, `COMPONENT_COMPACTRIFLE_CLIP_02`, `COMPONENT_ASSAULTRIFLE_MK2_CLIP_02`, `COMPONENT_CARBINERIFLE_MK2_CLIP_02`, `COMPONENT_SPECIALCARBINE_MK2_CLIP_02`, `COMPONENT_BULLPUPRIFLE_MK2_CLIP_02`}, useTime = 2500 },
	['at_clip_extended_mg'] = { component = {`COMPONENT_MG_CLIP_02`, `COMPONENT_COMBATMG_CLIP_02`, `COMPONENT_GUSENBERG_CLIP_02`}, useTime = 2500 },
	['at_clip_extended_sniper'] = { component = {`COMPONENT_MARKSMANRIFLE_CLIP_02`, `COMPONENT_HEAVYSNIPER_MK2_CLIP_02`, `COMPONENT_MARKSMANRIFLE_MK2_CLIP_02`}, useTime = 2500 },
	['at_compensator_pistol'] = { component = {`COMPONENT_AT_PI_COMP_02`, `COMPONENT_AT_PI_COMP_03`, `COMPONENT_AT_PI_COMP`}, useTime = 2500 },
	['at_suppressor_pistol'] = { component = {`COMPONENT_AT_PI_SUPP_02`, `COMPONENT_AT_AR_SUPP_02`, `COMPONENT_AT_PI_SUPP`}, useTime = 2500 },
	['at_suppresor_rifle'] = { component = {`COMPONENT_AT_AR_SUPP_02`, `COMPONENT_AT_AR_SUPP`}, useTime = 2500 },
	['at_suppresor_shotgun'] = { component = {`COMPONENT_AT_SR_SUPP`, `COMPONENT_AT_AR_SUPP`, `COMPONENT_AT_AR_SUPP_02`, `COMPONENT_AT_SR_SUPP_03`}, useTime = 2500 },
	['at_suppresor_smg'] = { component = {`COMPONENT_AT_AR_SUPP_02`, `COMPONENT_AT_PI_SUPP`}, useTime = 2500 },
	['at_suppresor_sniper'] = { component = {`COMPONENT_AT_AR_SUPP`, `COMPONENT_AT_SR_SUPP_03`}, useTime = 2500 },
	['at_clip_drum_pistol'] = { component = {`COMPONENT_MACHINEPISTOL_CLIP_03`}, useTime = 2500 },
	['at_clip_drum_rifle'] = { component = {`COMPONENT_COMPACTRIFLE_CLIP_03`, `COMPONENT_CARBINERIFLE_CLIP_03`, `COMPONENT_SPECIALCARBINE_CLIP_03`}, useTime = 2500 },
	['at_clip_drum_shotgun'] = { component = {`COMPONENT_HEAVYSHOTGUN_CLIP_03`}, useTime = 2500 },
	['at_clip_drum_smg'] = { component = {`COMPONENT_SMG_CLIP_03`, `COMPONENT_COMBATPDW_CLIP_03`}, useTime = 2500 },
	['at_scope_smg'] = { component = {`COMPONENT_AT_SCOPE_MACRO_02`, `COMPONENT_AT_SCOPE_MACRO`, `COMPONENT_AT_SCOPE_SMALL`}, useTime = 2500 },
	['at_scope_rifle'] = { component = {`COMPONENT_AT_SCOPE_MACRO`, `COMPONENT_AT_SCOPE_MEDIUM`, `COMPONENT_AT_SCOPE_SMALL`, `COMPONENT_AT_SCOPE_SMALL_02`}, useTime = 2500 },
	['at_scope_mg'] = { component = {`COMPONENT_AT_SCOPE_SMALL_02`, `COMPONENT_AT_SCOPE_MEDIUM`, `COMPONENT_AT_SCOPE_MEDIUM_MK2`}, useTime = 2500 },
	['at_scope_small_mg'] = { component = {`COMPONENT_AT_SCOPE_SMALL_MK2`}, useTime = 2500 },
	['at_scope_sniper'] = { component = {`COMPONENT_AT_SCOPE_MAX`}, useTime = 2500 },
	['at_scope_large_sniper'] = { component = {`COMPONENT_AT_SCOPE_LARGE_MK2`}, useTime = 2500 },
	['at_scope_nightvision_sniper'] = { component = {`COMPONENT_AT_SCOPE_NV`}, useTime = 2500 },
	['at_scope_thermal_sniper'] = { component = {`COMPONENT_AT_SCOPE_THERMAL`}, useTime = 2500 },
	['at_scope_small_shotgun'] = { component = {`COMPONENT_AT_SCOPE_SMALL_MK2`}, useTime = 2500 },
	['at_scope_macro_shotgun'] = { component = {`COMPONENT_AT_SCOPE_MACRO_MK2`}, useTime = 2500 },
	['at_scope_small_rifle'] = { component = {`COMPONENT_AT_SCOPE_SMALL_MK2`}, useTime = 2500 },
	['at_scope_macro_rifle'] = { component = {`COMPONENT_AT_SCOPE_MACRO_02_MK2`, `COMPONENT_AT_SCOPE_MACRO_MK2`}, useTime = 2500 },
	['at_scope_medium_rifle'] = { component = {`COMPONENT_AT_SCOPE_MEDIUM_MK2`}, useTime = 2500 },
	['at_scope_small_pistol'] = { component = {`COMPONENT_AT_SCOPE_SMALL_MK2`}, useTime = 2500 },
	['at_scope_macro_pistol'] = { component = {`COMPONENT_AT_SCOPE_MACRO_MK2`}, useTime = 2500 },
	['at_scope_mounted_pistol'] = { component = {`COMPONENT_AT_PI_RAIL_02`}, useTime = 2500 },
	['at_grip_smg'] = { component = {`COMPONENT_AT_AR_AFGRIP`}, useTime = 2500 },
	['at_grip_rifle'] = { component = {`COMPONENT_AT_AR_AFGRIP`, `COMPONENT_AT_AR_AFGRIP_02`}, useTime = 2500 },
	['at_grip_shotgun'] = { component = {`COMPONENT_AT_AR_AFGRIP`, `COMPONENT_AT_AR_AFGRIP_02`}, useTime = 2500 },
	['at_grip_mg'] = { component = {`COMPONENT_AT_AR_AFGRIP`, `COMPONENT_AT_AR_AFGRIP_02`}, useTime = 2500 },
	['at_grip_sniper'] = { component = {`COMPONENT_AT_AR_AFGRIP`, `COMPONENT_AT_AR_AFGRIP_02`}, useTime = 2500 },
	['at_barrel_shotgun'] = { component = {`COMPONENT_AT_SC_BARREL_02`}, useTime = 2500 },
	['at_barrel_rifle'] = { component = {`COMPONENT_AT_SC_BARREL_02`, `COMPONENT_AT_CR_BARREL_02`, `COMPONENT_AT_SC_BARREL_02`, `COMPONENT_AT_BP_BARREL_02`}, useTime = 2500 },
	['at_barrel_mg'] = { component = {`COMPONENT_AT_MG_BARREL_02`}, useTime = 2500 },
	['at_barrel_heavy_sniper'] = { component = {`COMPONENT_AT_MRFL_BARREL_02`}, useTime = 2500 },
	['at_muzzle_bellend_sniper'] = { component = {`COMPONENT_AT_SR_BARREL_01`}, useTime = 2500 },
	['at_muzzle_shotgun'] = { component = {`COMPONENT_AT_MUZZLE_08`}, useTime = 2500 },
	['at_muzzle_flat_rifle'] = { component = {`COMPONENT_AT_MUZZLE_01`}, useTime = 2500 },
	['at_muzzle_tatical_rifle'] = { component = {`COMPONENT_AT_MUZZLE_02`}, useTime = 2500 },
	['at_muzzle_fat_rifle'] = { component = {`COMPONENT_AT_MUZZLE_03`}, useTime = 2500 },
	['at_muzzle_precision_rifle'] = { component = {`COMPONENT_AT_MUZZLE_04`}, useTime = 2500 },
	['at_muzzle_heavy_rifle'] = { component = {`COMPONENT_AT_MUZZLE_05`}, useTime = 2500 },
	['at_muzzle_slanted_rifle'] = { component = {`COMPONENT_AT_MUZZLE_06`}, useTime = 2500 },
	['at_muzzle_split_rifle'] = { component = {`COMPONENT_AT_MUZZLE_07`}, useTime = 2500 },	
	['at_skin_pistol_gold'] = { component = {`COMPONENT_PISTOL_VARMOD_LUXE`, `COMPONENT_PISTOL50_VARMOD_LUXE`, `COMPONENT_APPISTOL_VARMOD_LUXE`, `COMPONENT_COMBATPISTOL_VARMOD_LOWRIDER`}, useTime = 2500 },
	['at_skin_pistol_camo'] = { component = {`COMPONENT_SNSPISTOL_MK2_CAMO`, `COMPONENT_REVOLVER_MK2_CAMO`, `COMPONENT_PISTOL_MK2_CAMO`}, useTime = 2500 },
	['at_skin_pistol_brushstroke'] = { component = {`COMPONENT_PISTOL_MK2_CAMO_02`, `COMPONENT_REVOLVER_MK2_CAMO_02`, `COMPONENT_SNSPISTOL_MK2_CAMO_02`}, useTime = 2500 },
	['at_skin_pistol_woodland'] = { component = {`COMPONENT_PISTOL_MK2_CAMO_03`, `COMPONENT_REVOLVER_MK2_CAMO_03`, `COMPONENT_SNSPISTOL_MK2_CAMO_03`}, useTime = 2500 },
	['at_skin_pistol_skull'] = { component = {`COMPONENT_PISTOL_MK2_CAMO_04`, `COMPONENT_REVOLVER_MK2_CAMO_04`, `COMPONENT_SNSPISTOL_MK2_CAMO_04`}, useTime = 2500 },
	['at_skin_pistol_sessanta'] = { component = {`COMPONENT_PISTOL_MK2_CAMO_05`, `COMPONENT_REVOLVER_MK2_CAMO_05`, `COMPONENT_SNSPISTOL_MK2_CAMO_05`}, useTime = 2500 },
	['at_skin_pistol_perseus'] = { component = {`COMPONENT_PISTOL_MK2_CAMO_06`, `COMPONENT_REVOLVER_MK2_CAMO_06`, `COMPONENT_SNSPISTOL_MK2_CAMO_06`}, useTime = 2500 },
	['at_skin_pistol_leopard'] = { component = {`COMPONENT_PISTOL_MK2_CAMO_07`, `COMPONENT_REVOLVER_MK2_CAMO_07`, `COMPONENT_SNSPISTOL_MK2_CAMO_07`}, useTime = 2500 },
	['at_skin_pistol_zebra'] = { component = {`COMPONENT_PISTOL_MK2_CAMO_08`, `COMPONENT_REVOLVER_MK2_CAMO_08`, `COMPONENT_SNSPISTOL_MK2_CAMO_08`}, useTime = 2500 },
	['at_skin_pistol_geometric'] = { component = {`COMPONENT_PISTOL_MK2_CAMO_09`, `COMPONENT_REVOLVER_MK2_CAMO_09`, `COMPONENT_SNSPISTOL_MK2_CAMO_09`}, useTime = 2500 },
	['at_skin_pistol_boom'] = { component = {`COMPONENT_PISTOL_MK2_CAMO_10`, `COMPONENT_REVOLVER_MK2_CAMO_10`, `COMPONENT_SNSPISTOL_MK2_CAMO_10`}, useTime = 2500 },
	['at_skin_pistol_patriotic'] = { component = {`COMPONENT_SNSPISTOL_MK2_CAMO_IND_01_SLIDE`, `COMPONENT_REVOLVER_MK2_CAMO_IND_01`, `COMPONENT_PISTOL_MK2_CAMO_IND_01`}, useTime = 2500 },
	['at_skin_rifle_gold'] = { component = {`COMPONENT_ASSAULTRIFLE_VARMOD_LUXE`, `COMPONENT_CARBINERIFLE_VARMOD_LUXE`, `COMPONENT_ADVANCEDRIFLE_VARMOD_LUXE`, `COMPONENT_SPECIALCARBINE_VARMOD_LOWRIDER`, `COMPONENT_BULLPUPRIFLE_VARMOD_LOW`, `COMPONENT_MG_VARMOD_LOWRIDER`}, useTime = 2500 },
	['at_skin_rifle_camo'] = { component = {`COMPONENT_ASSAULTRIFLE_MK2_CAMO`, `COMPONENT_CARBINERIFLE_MK2_CAMO`, `COMPONENT_SPECIALCARBINE_MK2_CAMO`, `COMPONENT_BULLPUPRIFLE_MK2_CAMO`, `COMPONENT_BULLPUPRIFLE_VARMOD_LOW`, `COMPONENT_MG_VARMOD_LOWRIDER`}, useTime = 2500 },
	['at_skin_rifle_brushstroke'] = { component = {`COMPONENT_ASSAULTRIFLE_MK2_CAMO_02`, `COMPONENT_CARBINERIFLE_MK2_CAMO_02`, `COMPONENT_SPECIALCARBINE_MK2_CAMO_02`, `COMPONENT_BULLPUPRIFLE_MK2_CAMO_02`}, useTime = 2500 },
	['at_skin_rifle_woodland'] = { component = {`COMPONENT_ASSAULTRIFLE_MK2_CAMO_03`, `COMPONENT_CARBINERIFLE_MK2_CAMO_03`, `COMPONENT_SPECIALCARBINE_MK2_CAMO_03`, `COMPONENT_BULLPUPRIFLE_MK2_CAMO_03`}, useTime = 2500 },
	['at_skin_rifle_skull'] = { component = {`COMPONENT_ASSAULTRIFLE_MK2_CAMO_04`, `COMPONENT_CARBINERIFLE_MK2_CAMO_04`, `COMPONENT_SPECIALCARBINE_MK2_CAMO_04`, `COMPONENT_BULLPUPRIFLE_MK2_CAMO_04`}, useTime = 2500 },
	['at_skin_rifle_sessanta'] = { component = {`COMPONENT_ASSAULTRIFLE_MK2_CAMO_05`, `COMPONENT_CARBINERIFLE_MK2_CAMO_05`, `COMPONENT_SPECIALCARBINE_MK2_CAMO_05`, `COMPONENT_BULLPUPRIFLE_MK2_CAMO_05`}, useTime = 2500 },
	['at_skin_rifle_perseus'] = { component = {`COMPONENT_ASSAULTRIFLE_MK2_CAMO_06`, `COMPONENT_CARBINERIFLE_MK2_CAMO_06`, `COMPONENT_SPECIALCARBINE_MK2_CAMO_06`, `COMPONENT_BULLPUPRIFLE_MK2_CAMO_06`}, useTime = 2500 },
	['at_skin_rifle_leopard'] = { component = {`COMPONENT_ASSAULTRIFLE_MK2_CAMO_07`, `COMPONENT_CARBINERIFLE_MK2_CAMO_07`, `COMPONENT_SPECIALCARBINE_MK2_CAMO_07`, `COMPONENT_BULLPUPRIFLE_MK2_CAMO_07`}, useTime = 2500 },
	['at_skin_rifle_zebra'] = { component = {`COMPONENT_ASSAULTRIFLE_MK2_CAMO_08`, `COMPONENT_CARBINERIFLE_MK2_CAMO_08`, `COMPONENT_SPECIALCARBINE_MK2_CAMO_08`, `COMPONENT_BULLPUPRIFLE_MK2_CAMO_08`}, useTime = 2500 },
	['at_skin_rifle_geometric'] = { component = {`COMPONENT_ASSAULTRIFLE_MK2_CAMO_09`, `COMPONENT_CARBINERIFLE_MK2_CAMO_09`, `COMPONENT_SPECIALCARBINE_MK2_CAMO_09`, `COMPONENT_BULLPUPRIFLE_MK2_CAMO_09`}, useTime = 2500 },
	['at_skin_rifle_boom'] = { component = {`COMPONENT_ASSAULTRIFLE_MK2_CAMO_10`, `COMPONENT_CARBINERIFLE_MK2_CAMO_10`, `COMPONENT_SPECIALCARBINE_MK2_CAMO_10`, `COMPONENT_BULLPUPRIFLE_MK2_CAMO_10`}, useTime = 2500 },
	['at_skin_rifle_patriotic'] = { component = {`COMPONENT_ASSAULTRIFLE_MK2_CAMO_IND_01`, `COMPONENT_CARBINERIFLE_MK2_CAMO_IND_01`, `COMPONENT_SPECIALCARBINE_MK2_CAMO_IND_01`, `COMPONENT_BULLPUPRIFLE_MK2_CAMO_IND_01`}, useTime = 2500 },
	['at_skin_shotgun_gold'] = { component = {`COMPONENT_PUMPSHOTGUN_VARMOD_LOWRIDER`, `COMPONENT_SAWNOFFSHOTGUN_VARMOD_LUXE`}, useTime = 2500 },
	['at_skin_shotgun_camo'] = { component = {`COMPONENT_PUMPSHOTGUN_MK2_CAMO`}, useTime = 2500 },
	['at_skin_shotgun_brushstroke'] = { component = {`COMPONENT_PUMPSHOTGUN_MK2_CAMO_02`}, useTime = 2500 },
	['at_skin_shotgun_woodland'] = { component = {`COMPONENT_PUMPSHOTGUN_MK2_CAMO_03`}, useTime = 2500 },
	['at_skin_shotgun_skull'] = { component = {`COMPONENT_PUMPSHOTGUN_MK2_CAMO_04`}, useTime = 2500 },
	['at_skin_shotgun_sessanta'] = { component = {`COMPONENT_PUMPSHOTGUN_MK2_CAMO_05`}, useTime = 2500 },
	['at_skin_shotgun_perseus'] = { component = {`COMPONENT_PUMPSHOTGUN_MK2_CAMO_06`}, useTime = 2500 },
	['at_skin_shotgun_leopard'] = { component = {`COMPONENT_PUMPSHOTGUN_MK2_CAMO_07`}, useTime = 2500 },
	['at_skin_shotgun_zebra'] = { component = {`COMPONENT_PUMPSHOTGUN_MK2_CAMO_08`}, useTime = 2500 },
	['at_skin_shotgun_geometric'] = { component = {`COMPONENT_PUMPSHOTGUN_MK2_CAMO_09`}, useTime = 2500 },
	['at_skin_shotgun_boom'] = { component = {`COMPONENT_PUMPSHOTGUN_MK2_CAMO_10`}, useTime = 2500 },
	['at_skin_shotgun_patriotic'] = { component = {`COMPONENT_PUMPSHOTGUN_MK2_CAMO_IND_01`}, useTime = 2500 },
	['at_skin_mg_gold'] = { component = {`COMPONENT_MARKSMANRIFLE_VARMOD_LUXE`, `COMPONENT_SNIPERRIFLE_VARMOD_LUXE`}, useTime = 2500 },
	['at_skin_mg_camo'] = { component = {`COMPONENT_COMBATMG_MK2_CAMO`}, useTime = 2500 },
	['at_skin_mg_brushstroke'] = { component = {`COMPONENT_COMBATMG_MK2_CAMO_02`}, useTime = 2500 },
	['at_skin_mg_woodland'] = { component = {`COMPONENT_COMBATMG_MK2_CAMO_03`}, useTime = 2500 },
	['at_skin_mg_skull'] = { component = {`COMPONENT_COMBATMG_MK2_CAMO_04`}, useTime = 2500 },
	['at_skin_mg_sessanta'] = { component = {`COMPONENT_COMBATMG_MK2_CAMO_05`}, useTime = 2500 },
	['at_skin_mg_perseus'] = { component = {`COMPONENT_COMBATMG_MK2_CAMO_06`}, useTime = 2500 },
	['at_skin_mg_leopard'] = { component = {`COMPONENT_COMBATMG_MK2_CAMO_07`}, useTime = 2500 },
	['at_skin_mg_zebra'] = { component = {`COMPONENT_COMBATMG_MK2_CAMO_08`}, useTime = 2500 },
	['at_skin_mg_geometric'] = { component = {`COMPONENT_COMBATMG_MK2_CAMO_09`}, useTime = 2500 },
	['at_skin_mg_boom'] = { component = {`COMPONENT_COMBATMG_MK2_CAMO_10`}, useTime = 2500 },
	['at_skin_mg_patriotic'] = { component = {`COMPONENT_COMBATMG_MK2_CAMO_IND_01`}, useTime = 2500 },
	['at_skin_sniper_camo'] = { component = {`COMPONENT_HEAVYSNIPER_MK2_CAMO`, `COMPONENT_MARKSMANRIFLE_MK2_CAMO`}, useTime = 2500 },
	['at_skin_sniper_brushstroke'] = { component = {`COMPONENT_HEAVYSNIPER_MK2_CAMO_02`, `COMPONENT_MARKSMANRIFLE_MK2_CAMO_02`}, useTime = 2500 },
	['at_skin_sniper_woodland'] = { component = {`COMPONENT_HEAVYSNIPER_MK2_CAMO_03`, `COMPONENT_MARKSMANRIFLE_MK2_CAMO_03`}, useTime = 2500 },
	['at_skin_sniper_skull'] = { component = {`COMPONENT_HEAVYSNIPER_MK2_CAMO_04`, `COMPONENT_MARKSMANRIFLE_MK2_CAMO_04`}, useTime = 2500 },
	['at_skin_sniper_sessanta'] = { component = {`COMPONENT_HEAVYSNIPER_MK2_CAMO_05`, `COMPONENT_MARKSMANRIFLE_MK2_CAMO_05`}, useTime = 2500 },
	['at_skin_sniper_perseus'] = { component = {`COMPONENT_HEAVYSNIPER_MK2_CAMO_06`, `COMPONENT_MARKSMANRIFLE_MK2_CAMO_06`}, useTime = 2500 },
	['at_skin_sniper_leopard'] = { component = {`COMPONENT_HEAVYSNIPER_MK2_CAMO_07`, `COMPONENT_MARKSMANRIFLE_MK2_CAMO_07`}, useTime = 2500 },
	['at_skin_sniper_zebra'] = { component = {`COMPONENT_HEAVYSNIPER_MK2_CAMO_08`, `COMPONENT_MARKSMANRIFLE_MK2_CAMO_08`}, useTime = 2500 },
	['at_skin_sniper_geometric'] = { component = {`COMPONENT_HEAVYSNIPER_MK2_CAMO_09`, `COMPONENT_MARKSMANRIFLE_MK2_CAMO_09`}, useTime = 2500 },
	['at_skin_sniper_boom'] = { component = {`COMPONENT_HEAVYSNIPER_MK2_CAMO_10`, `COMPONENT_MARKSMANRIFLE_MK2_CAMO_10`}, useTime = 2500 },
	['at_skin_sniper_patriotic'] = { component = {`COMPONENT_HEAVYSNIPER_MK2_CAMO_IND_01`, `COMPONENT_MARKSMANRIFLE_MK2_CAMO_IND_01`}, useTime = 2500 },
	['at_skin_sniper_gold'] = { component = {`COMPONENT_MARKSMANRIFLE_VARMOD_LUXE`}, useTime = 2500 },

	['burger'] = {
		hunger = 200000,
		animDict = 'mp_player_inteat@burger',
		anim = 'mp_player_int_eat_burger_fp',
		model = 'prop_cs_burger_01',
		coords = { x = 0.02, y = 0.022, z = -0.02 },
		rotation = { x = 0.0, y = 5.0, z = 0.0 },
		useTime = 2500,
		event = 'linden_inventory:burger'
	},

	['water'] = {
		thirst = 200000,
		animDict = 'mp_player_intdrink',
		anim = 'loop_bottle',
		model = 'prop_ld_flow_bottle',
		coords = { x = 0.03, y = 0.0, z = 0.02 },
		rotation = { x = 0.0, y = -13.5, z = -1.5 },
		useTime = 2500,
		event = 'linden_inventory:water'
	},

	['cola'] = {
		thirst = 200000,
		animDict = 'mp_player_intdrink',
		anim = 'loop_bottle',
		model = 'prop_ecola_can',
		coords = { x = 0.01, y = 0.0, z = 0.06 },
		rotation = { x = 5.0, y = -1.5, z = -180.5 },
		useTime = 2500,
		event = 'linden_inventory:cola'
	},

	['mustard'] = {
		thirst = 10000,
		hunger = 10000,
		animDict = 'mp_player_intdrink',
		anim = 'loop_bottle',
		model = 'prop_food_mustard',
		coords = { x = 0.01, y = 0.0, z = -0.07 },
		rotation = { x = 1.0, y = -1.0, z = -1.5 },
		useTime = 2500,
		event = 'linden_inventory:mustard'
	},

	['bandage'] = {
		animDict = 'missheistdockssetup1clipboard@idle_a',
		anim = 'idle_a',
		flags = 49,
		model = 'prop_rolled_sock_02',
		coords = { x = -0.14, y = 0.02, z = -0.08 },
		rotation = { x = -50.0, y = -50.0, z = 0.0 },
		useTime = 2500,
		event = 'linden_inventory:bandage'
	},

	['lockpick'] = {
		disableMove = true,
		animDict = 'anim@amb@clubhouse@tutorial@bkr_tut_ig3@',
		anim = 'machinic_loop_mechandplayer',
		useTime = 2000,
		consume = 0,
		dofirst = 'esx_lockpick:onUse'
	},

}
