Config.DurabilityDecrease = {
	['WEAPON_PISTOL'] = 0.6, 
	['WEAPON_ADVANCEDRIFLE'] = 0.6, 
	['WEAPON_APPISTOL'] = 0.4, 
	['WEAPON_ASSAULTRIFLE'] = 0.8, 
	['WEAPON_ASSAULTRIFLE_MK2'] = 0.6, 
	['WEAPON_ASSAULTSMG'] = 0.6, 
	['WEAPON_BALL'] = 1.0, 
	['WEAPON_BAT'] = 1.0, 
	['WEAPON_BATTLEAXE'] = 5.0, 
	['WEAPON_BOTTLE'] = 5.0, 
	['WEAPON_BULLPUPRIFLE'] = 0.9, 
	['WEAPON_BULLPUPRIFLE_MK2'] = 0.7, 
	['WEAPON_CARBINERIFLE'] = 0.8, 
	['WEAPON_CARBINERIFLE_MK2'] = 0.7, 
	['WEAPON_COMBATPDW'] = 3.0, 
	['WEAPON_COMBATPISTOL'] = 0.5, 
	['WEAPON_COMPACTRIFLE'] = 0.7, 
	['WEAPON_CROWBAR'] = 1.0, 
	['WEAPON_DAGGER'] = 1.0, 
	['WEAPON_DOUBLEACTION'] = 0.8, 
	['WEAPON_FLAREGUN'] = 1.0, 
	['WEAPON_FLASHLIGHT'] = 1.0, 
	['WEAPON_GOLFCLUB'] = 1.0, 
	['WEAPON_GUSENBERG'] = 0.8, 
	['WEAPON_HAMMER'] = 1.0, 
	['WEAPON_HATCHET'] = 1.0, 
	['WEAPON_HEAVYPISTOL'] = 0.6, 
	['WEAPON_KNIFE'] = 1.0, 
	['WEAPON_KNUCKLE'] = 1.0, 
	['WEAPON_MACHETE'] = 1.0, 
	['WEAPON_MACHINEPISTOL'] = 0.7, 
	['WEAPON_MARKSMANPISTOL'] = 4.0, 
	['WEAPON_MICROSMG'] = 0.6, 
	['WEAPON_MINISMG'] = 0.6, 
	['WEAPON_MOLOTOV'] = 5.0, 
	['WEAPON_MUSKET'] = 1.0, 
	['WEAPON_NIGHTSTICK'] = 1.0, 
	['WEAPON_PISTOL50'] = 0.8, 
	['WEAPON_PISTOL_MK2'] = 0.5, 
	['WEAPON_PUMPSHOTGUN'] = 0.8, 
	['WEAPON_PUMPSHOTGUN_MK2'] = 0.7, 
	['WEAPON_REVOLVER'] = 0.8, 
	['WEAPON_REVOLVER_MK2'] = 0.7, 
	['WEAPON_SAWNOFFSHOTGUN'] = 0.9, 
	['WEAPON_SMG'] = 0.8, 
	['WEAPON_SMG_MK2'] = 0.7, 
	['WEAPON_SNSPISTOL'] = 0.7, 
	['WEAPON_SNSPISTOL_MK2'] = 0.6, 
	['WEAPON_SPECIALCARBINE'] = 0.8, 
	['WEAPON_SPECIALCARBINE_MK2'] = 0.7, 
	['WEAPON_STONE_HATCHET'] = 1.0, 
	['WEAPON_STUNGUN'] = 0.6, 
	['WEAPON_SWITCHBLADE'] = 1.0, 
	['WEAPON_VINTAGEPISTOL'] = 0.7, 
	['WEAPON_WRENCH'] = 1.0
}

Config.Throwable = {
	['WEAPON_GRENADE']=1, 
	['WEAPON_BZGAS']=1, 
	['WEAPON_MOLOTOV']=1, 
	['WEAPON_STICKYBOMB']=1, 
	['WEAPON_PROXMINE']=1, 
	['WEAPON_SNOWBALL']=1, 
	['WEAPON_PIPEBOMB']=1, 
	['WEAPON_BALL']=1, 
	['WEAPON_SMOKEGRENADE']=1, 
	['WEAPON_FLARE']=1
}

Config.Melee = {
	['WEAPON_KNIFE']=1, 
	['WEAPON_DAGGER']=1, 
	['WEAPON_BAT']=1, 
	['WEAPON_BOTTLE']=1, 
	['WEAPON_CROWBAR']=1, 
	['WEAPON_FLASHLIGHT']=1, 
	['WEAPON_GOLFCLUB']=1, 
	['WEAPON_HAMMER']=1, 
	['WEAPON_HATCHET']=1, 
	['WEAPON_KNUCKLE']=1, 
	['WEAPON_MACHETE']=1, 
	['WEAPON_SWITCHBLADE']=1, 
	['WEAPON_NIGHTSTICK']=1, 
	['WEAPON_WRENCH']=1, 
	['WEAPON_BATTLEAXE']=1, 
	['WEAPON_POOLCUE']=1, 
	['WEAPON_STONE_HATCHET']=1
}

Config.Miscellaneous = {
	['WEAPON_PETROLCAN']=1, 
	['GADGET_PARACHUTE']=1, 
	['WEAPON_FIREEXTINGUISHER']=1, 
	['WEAPON_HAZARDCAN']=1
}

-- INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`, `stackable`, `closeonuse`, `description`) VALUES
-- 	('ammo-flare', 'Flare', 38, 0, 1, 1, 0, NULL),
-- 	('ammo-musket', 'Musket ammo', 30, 0, 1, 1, 0, NULL),
-- 	('ammo_lmg', 'LMG Ammo', 10, 0, 1, 1, 0, NULL),
-- 	('ammo_pistol', 'Pistol Ammo', 8, 0, 1, 1, 0, NULL),
-- 	('ammo_rifle', 'Rifle Ammo', 10, 0, 1, 1, 0, NULL),
-- 	('ammo_shotgun', 'Shotgun Ammo', 10, 0, 1, 1, 0, NULL),
-- 	('ammo_smg', 'SMG Ammo', 10, 0, 1, 1, 0, NULL),
-- 	('ammo_sniper', 'Sniper Ammo', 10, 0, 1, 1, 0, NULL);
Config.Ammos = {
	['ammo_pistol'] = {
		`WEAPON_HEAVYPISTOL`,
		`WEAPON_SNSPISTOL`,
		`WEAPON_SNSPISTOL_MK2`,
		`WEAPON_APPISTOL`,
		`WEAPON_COMBATPISTOL`,
		`WEAPON_MACHINEPISTOL`,
		`WEAPON_VINTAGEPISTOL`,
		`WEAPON_CERAMICPISTOL`,
		`WEAPON_MARKSMANPISTOL`,
		`WEAPON_PISTOL50`,
		`WEAPON_PISTOL`,
		`WEAPON_PISTOL_MK2`,
		`WEAPON_REVOLVER`,
		`WEAPON_REVOLVER_MK2`,
		`WEAPON_NAVYREVOLVER`,
		`WEAPON_DOUBLEACTION`
	},

	['ammo_shotgun'] = {
		`WEAPON_ASSAULTSHOTGUN`,
		`WEAPON_BULLPUPSHOTGUN`,
		`WEAPON_DBSHOTGUN`,
		`WEAPON_HEAVYSHOTGUN`,
		`WEAPON_PUMPSHOTGUN`,
		`WEAPON_PUMPSHOTGUN_MK2`,
		`WEAPON_SAWNOFFSHOTGUN`,
		`WEAPON_SWEEPERSHOTGUN`,
		`WEAPON_COMBATSHOTGUN`
	},

	['ammo_smg'] = {
		`WEAPON_GUSENBERG`,
		`WEAPON_MICROSMG`,
		`WEAPON_COMBATPDW`,
		`WEAPON_MINISMG`,
		`WEAPON_SMG`,
		`WEAPON_SMG_MK2`,
		`WEAPON_ASSAULTSMG`
	},

	['ammo_rifle'] = {
		`WEAPON_ADVANCEDRIFLE`,
		`WEAPON_BULLPUPRIFLE`,
		`WEAPON_BULLPUPRIFLE_MK2`,
		`WEAPON_CARBINERIFLE`,
		`WEAPON_CARBINERIFLE_MK2`,
		`WEAPON_SPECIALCARBINE`,
		`WEAPON_SPECIALCARBINE_MK2`,
		`WEAPON_MILITARYRIFLE`,
		`WEAPON_ASSAULTRIFLE`,
		`WEAPON_ASSAULTRIFLE_MK2`,
		`WEAPON_COMPACTRIFLE`
	},

	['ammo_lmg'] = {
		`WEAPON_COMBATMG`,
		`WEAPON_COMBATMG_MK2`,
		`WEAPON_MG`
	},

	['ammo_sniper'] = {
		`WEAPON_MARKSMANRIFLE`,
		`WEAPON_MARKSMANRIFLE_MK2`,
		`WEAPON_SNIPERRIFLE`,
		`WEAPON_HEAVYSNIPER`,
		`WEAPON_HEAVYSNIPER_MK2`
	},

	['ammo-flare'] = {
		`WEAPON_FLAREGUN`
	},

	['ammo-musket'] = {
		`WEAPON_MUSKET`
	},
}

Config.AmmoType = {}
function SetupAmmo()
	for k,v in pairs(Config.Ammos) do
		for k2, v2 in pairs(v) do
			Config.AmmoType[v2] = k
		end
	end
end
SetupAmmo()
function GetAmmoType(weapon)
	if type(weapon) == 'string' then weapon = GetHashKey(weapon) end
	return Config.AmmoType[weapon]
end
